max_width                       = 80
tab_spaces                      = 4
fn_brace_style                  = "AlwaysNextLine"
item_brace_style                = "AlwaysNextLine"
control_brace_style             = "AlwaysNextLine"
reorder_imports                 = true
wrap_comments                   = false
normalise_comments              = false
impl_empty_single_line          = true
fn_empty_single_line            = true
fn_single_line                  = false
chain_one_line_max              = 40
chain_split_single_child        = false
single_line_if_else_max_width   = 0
hard_tabs                       = false
indent_match_arms               = true
