max_width                       = 80
tab_spaces                      = 4
brace_style                     = "AlwaysNextLine"
control_brace_style             = "AlwaysSameLine"
reorder_imports                 = true
reorder_imports_in_group        = true
wrap_comments                   = false
normalise_comments              = false
impl_empty_single_line          = true
fn_empty_single_line            = true
fn_single_line                  = false
chain_width                     = 40
chain_split_single_child        = false
single_line_if_else_max_width   = 0
hard_tabs                       = false
indent_match_arms               = true
